# Generated by Django 4.0.4 on 2022-05-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instock',
            field=models.IntegerField(default=100),
        ),
    ]
